// <auto-generated />
using System;
using Amccloy.MusicBot.Net.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Amccloy.MusicBot.Net.Migrations
{
    [DbContext(typeof(TriviaContext))]
    partial class TriviaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("trivia_questions")
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Amccloy.MusicBot.Net.Dbo.MultiChoiceTriviaQuestionDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string[]>("FalseAnswers")
                        .HasColumnType("jsonb")
                        .HasColumnName("false_answers");

                    b.Property<string>("Question")
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_multi_choice_trivia_questions");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_multi_choice_trivia_questions_category");

                    b.HasIndex("Source")
                        .HasDatabaseName("ix_multi_choice_trivia_questions_source");

                    b.ToTable("multi_choice_trivia_questions", "trivia_questions");
                });

            modelBuilder.Entity("Amccloy.MusicBot.Net.Dbo.MusicTriviaQuestionDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Playlist")
                        .HasColumnType("text")
                        .HasColumnName("playlist");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_music_trivia_questions");

                    b.HasIndex("Playlist")
                        .HasDatabaseName("ix_music_trivia_questions_playlist");

                    b.HasIndex("Source")
                        .HasDatabaseName("ix_music_trivia_questions_source");

                    b.ToTable("music_trivia_questions", "trivia_questions");
                });

            modelBuilder.Entity("Amccloy.MusicBot.Net.Dbo.StandardTriviaQuestionDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Question")
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_standard_trivia_questions");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_standard_trivia_questions_category");

                    b.HasIndex("Source")
                        .HasDatabaseName("ix_standard_trivia_questions_source");

                    b.ToTable("standard_trivia_questions", "trivia_questions");
                });

            modelBuilder.Entity("Amccloy.MusicBot.Net.Dbo.MusicTriviaQuestionDbo", b =>
                {
                    b.OwnsOne("Amccloy.MusicBot.Net.Dbo.Song", "Song", b1 =>
                        {
                            b1.Property<int>("MusicTriviaQuestionDboId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Album")
                                .HasColumnType("text")
                                .HasColumnName("song_album");

                            b1.Property<string>("Artist")
                                .HasColumnType("text")
                                .HasColumnName("song_artist");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("song_name");

                            b1.Property<string>("OriginalArtist")
                                .HasColumnType("text")
                                .HasColumnName("song_original_artist");

                            b1.Property<string>("Year")
                                .HasColumnType("text")
                                .HasColumnName("song_year");

                            b1.HasKey("MusicTriviaQuestionDboId");

                            b1.ToTable("music_trivia_questions", "trivia_questions");

                            b1.WithOwner()
                                .HasForeignKey("MusicTriviaQuestionDboId")
                                .HasConstraintName("fk_music_trivia_questions_music_trivia_questions_id");
                        });

                    b.Navigation("Song");
                });
#pragma warning restore 612, 618
        }
    }
}
